url: "https://restapia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/RestApia.Portal" # the subpath of your site, e.g. /blog
title: "RestApia - Desktop tool" # the name of your site, e.g. ACME Corp.
